/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FromMain;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author huyph
 */
public class frmChuongTrinh extends javax.swing.JFrame {

    /**
     * Creates new form frmChuongTrinh
     */
    public frmChuongTrinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthoat = new javax.swing.JButton();
        btnPlay1 = new javax.swing.JButton();
        btnQuanLyQH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHỌN CÁC CHỨC NĂNG CỦA CHƯƠNG TRÌNH");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hình/exit.png"))); // NOI18N
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnthoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 40, 60, 60));

        btnPlay1.setBackground(new java.awt.Color(102, 0, 153));
        btnPlay1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPlay1.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hình/Play-.png"))); // NOI18N
        btnPlay1.setText("CHƠI GAME");
        btnPlay1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlay1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 200, 60));

        btnQuanLyQH.setBackground(new java.awt.Color(99, 0, 153));
        btnQuanLyQH.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnQuanLyQH.setForeground(new java.awt.Color(255, 255, 255));
        btnQuanLyQH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hình/Setting.png"))); // NOI18N
        btnQuanLyQH.setText("QUẢN LÝ CH");
        btnQuanLyQH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyQH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyQHActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLyQH, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 200, 60));

        jLabel1.setBackground(new java.awt.Color(102, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hình/bg-top8.png"))); // NOI18N
        jLabel1.setText("hình nền");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        int mh = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thoát Chương Trình ??", "Thông Báo", JOptionPane.YES_OPTION);
        if (mh == JOptionPane.YES_OPTION){
            this.dispose();
        }
        
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlay1ActionPerformed
        Play qlcg = null;
        try {
            qlcg = new Play();
        } catch (SQLException ex) {
            Logger.getLogger(frmChuongTrinh.class.getName()).log(Level.SEVERE, null, ex);
        }
        qlcg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlay1ActionPerformed

    private void btnQuanLyQHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyQHActionPerformed
        DangNhap qlcg= new DangNhap();
        qlcg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuanLyQHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChuongTrinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChuongTrinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay1;
    private javax.swing.JButton btnQuanLyQH;
    private javax.swing.JButton btnthoat;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
